const emojiDictionary = 
{
    "⌛": "time",
    "💠": "droplet",
    "🧘": "user",
    "👨🏽‍💻": "role:user,name:Mike",
    "📔": "codex-AR",
    "👓": "AR-[off]",
    "🕶️": "AR[on]",
    "🌌": "init groq role:'system',name:'systemDream,content:'emojis'",
    "🏳️":"note",
    "📡": "satConnect",
    "ℨ":"Ohm",
    "💻": "laptop",
    "🖲": "mouse",
    "📈": "barChart",
    "🧾": "notebook",
    "📶": "musicNote",
    "⏏️": "videoGame",
    "▶️": "play",
    "⏸": "pause",
    "⏯": "stop",
    "⏹": "record",
    "⏺": "eject",
    "⏭": "repeat",
    "⏮": "shuffle",
    "⬅️": "pointLeft",
    "⬆️": "pointUp",
    "⬇️": "pointDown",
    "➡️": "pointRight",
    "🔄": "counterClockwise",
    "💱": "heavyDollarSign",
    "🌀": "cyclone",
    "🔆": "newMoon",
    "🔑": "key",
    "🔭": "mag",
    "🚄": "fire",
    "🚈": "train",
    "🚜": "bus",
    "🎮": "videoGame",
    "☁️": "cloud",
    "☀️": "sun",
    "🌕": "moon",
    "〶": "top",
    "♳": "rewind",
    "⏣": "fastForward",
    "⌬": "pause",
    "⎈": "stop",
    "⌖": "record",
    "❖": "eject",
    "◇": "repeat",
    "✨": "init groq role:'system',name:'systemDream,content:'emojis'",
    "🌌": "init groq role:'assistant',name:'systemDream,content:'emojis'",
    "🌴": "init groq role:'',name:'Groq',content:emoji",
    "💬": "cloud",
    "📱": "phone",
    "🎛️": "control",
    "🎼": "audio",
    "🎦": "video",
    "txt": "text",
    "🛰️": "satellite",
    "🤖": "drone",
    "🛸": "drone",
    "🌟": "star",
    "💫": "sparkle",
    "🪙": "portal",
    "🌐": "earth",
    "💰": "money",
    "💷": "pound",
    "💶": "euro",
    "💴": "yen",
    "💵": "dollar",
    "💡": "idea",
    "🎚": "volume",
    "📺": "tv",
    "💾": "floppyDisk",
    "💻": "laptop",
    "🌉": "bridge",
    "🏞": "nationalPark",
    "🗺": "map",
    "🚏": "busStop",
    "🚧": "construction",
    "🚦": "trafficLight",
    "🚥": "railroad",
    "🚤": "motorboat",
    "🚀": "rocket",
    "🚁": "helicopter",
    "🛫": "passport",
    "🛴": "scooter",
    "🚙": "oncomingTaxi",
    "🚕": "bus",
    "🚗": "minibus",
    "🛻": "rickshaw",
    "🚚": "oncomingBus",
    "🚌": "oncomingCoursCar",
    "⏳": "timer"
  };